import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/utils/supabase/server";
import { CopyButton } from "@/components/CopyButton";
import { Target, Users, DollarSign, GitMerge, ArrowRight, Lightbulb } from "lucide-react";
import Link from "next/link";
import { AffiliateQuickViewButton } from "@/app/(admin)/admin/referrals/AffiliateQuickViewButton";
import { AffiliateActionsCell } from "@/app/(admin)/admin/affiliates/AffiliateActionsCell";
import { AdminSetupChecklist } from "./AdminSetupChecklist";
import { CountUp } from "@/components/CountUp";

export default async function AdminDashboard() {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  const { data: org } = await supabase
    .from('organizations')
    .select('id, stripe_webhook_id, custom_domain')
    .eq('owner_id', user?.id || 'NO_USER')
    .limit(1)
    .maybeSingle();

  const orgId = org?.id;

  if (!orgId) {
      return (
          <div className="flex h-full items-center justify-center p-8">
              <div className="bg-zinc-900 border border-red-500/30 text-amber-500/80 px-6 py-4 rounded-xl shadow-xl max-w-md text-center text-sm font-mono tracking-wide">
                  Organization configuration missing or unauthorized. Please verify your platform status.
              </div>
          </div>
      );
  }

  const portalUrl = org?.custom_domain ? `https://${org.custom_domain}` : (process.env.NEXT_PUBLIC_SITE_URL || "https://affiliatemango.com");

  // Fetch real aggregated data
  const { count: affiliatesCount } = await supabase
    .from('affiliates')
    .select('*', { count: 'exact', head: true })
    .eq('org_id', orgId);

  const { data: stats } = await supabase
    .from('affiliates')
    .select('clicks, total_commission')
    .eq('org_id', orgId);

  const totalClicks = stats?.reduce((acc, curr) => acc + (curr.clicks || 0), 0) || 0;
  const totalCommissions = stats?.reduce((acc, curr) => acc + Number(curr.total_commission || 0), 0) || 0;
  const estimatedRevenue = totalCommissions * 3.33;

  const { data: campaigns } = await supabase.from("campaigns").select("*").eq('org_id', orgId);

  // Recent referrals (actually recent sales/commissions) mapped to precise events
  const { data: recentCommissions } = await supabase
    .from("commissions")
    .select("id, amount, revenue, status, affiliate_id, created_at, customer_email, referral:referrals(customer_email)")
    .eq('org_id', orgId)
    .order("created_at", { ascending: false })
    .limit(8);

  const recentAffIds = [...new Set((recentCommissions || []).map((c: any) => c.affiliate_id).filter(Boolean))];
  const { data: recentAffiliates } = recentAffIds.length > 0
    ? await supabase.from("affiliates").select("*").in("id", recentAffIds)
    : { data: [] };

  const recentAffMap: Record<string, any> = {};
  for (const a of recentAffiliates || []) recentAffMap[a.id] = a;

  // Track settlements to know if these are "paid" or "pending" dynamically
  const { data: recentPayouts } = await supabase.from("payouts").select("affiliate_id, created_at").eq("org_id", orgId);
  const payoutMap: Record<string, Date[]> = {};
  for (const p of recentPayouts || []) {
      if (!payoutMap[p.affiliate_id]) payoutMap[p.affiliate_id] = [];
      payoutMap[p.affiliate_id].push(new Date(p.created_at));
  }

  const recentReferrals = (recentCommissions || []).map((c: any) => {
    let email = c.customer_email;
    if (!email && c.referral && !Array.isArray(c.referral)) {
        email = c.referral.customer_email || "Unknown";
    }

    const dates = payoutMap[c.affiliate_id] || [];
    const commDate = new Date(c.created_at);
    const settled = dates.some(pd => pd >= commDate);
    const effectiveStatus = settled ? 'paid' : (c.status || 'pending');

    return {
      id: c.id,
      customer_email: email,
      status: effectiveStatus,
      totalRevenue: Number(c.revenue || 0),
      totalCommission: Number(c.amount || 0),
      affiliate: c.affiliate_id ? recentAffMap[c.affiliate_id] ?? null : null,
      created_at: c.created_at
    };
  });

  return (
    <div className="space-y-6 w-full max-w-full font-sans pb-10">
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 mb-10 mt-2">
        <div>
          <h2 className="text-4xl md:text-[2.75rem] font-extrabold text-white tracking-tight leading-tight">
            <CountUp end={estimatedRevenue} prefix="$" decimals={2} /> <span className="text-zinc-400 font-medium text-2xl md:text-[1.75rem]">generated by your affiliates</span>
          </h2>
          <p className="text-lg text-emerald-400 font-medium mt-3 flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.8)] animate-pulse" />
            <CountUp end={affiliatesCount || 0} /> affiliates are actively sending traffic
          </p>
        </div>
        <div className="flex flex-col items-end gap-3 shrink-0">
          <Link href="/admin/affiliates" className="bg-orange-500 hover:bg-orange-400 text-black font-extrabold px-8 py-3.5 rounded-xl shadow-[0_0_20px_rgba(249,115,22,0.4)] transition-all hover:scale-105 active:scale-95 text-center">
              Invite more affiliates
          </Link>
          <select className="bg-zinc-900 border border-zinc-800 text-sm px-4 py-2 hover:border-zinc-700 rounded-lg text-zinc-300 focus:outline-none focus:ring-1 focus:ring-orange-500 transition-all cursor-pointer hover:bg-zinc-800 w-full md:w-auto text-right">
            <option>Last 7 days</option>
            <option>Last 30 days</option>
            <option>All time</option>
          </select>
        </div>
      </div>

      <AdminSetupChecklist 
        hasCampaign={!!(campaigns && campaigns.length > 0)}
        hasAffiliate={!!(affiliatesCount && affiliatesCount > 0)}
        hasClicks={totalClicks > 0}
        hasStripe={!!org?.stripe_webhook_id}
      />

      {(!affiliatesCount || affiliatesCount === 0) ? (
        <div className="bg-zinc-900 border border-zinc-800/80 rounded-xl py-20 px-6 text-center shadow-2xl relative overflow-hidden mt-8 mb-10">
            <h3 className="text-3xl font-extrabold text-zinc-100 mb-4 relative z-10 tracking-tight">You don't have affiliates yet</h3>
            <p className="text-lg text-zinc-400 mb-8 max-w-xl mx-auto relative z-10 font-medium">Start by inviting your first 5 affiliates to kick off your growth engine.</p>
            <Link href="/admin/affiliates" className="inline-flex items-center justify-center bg-orange-500 hover:bg-orange-400 text-black font-extrabold px-8 py-4 rounded-xl shadow-[0_0_25px_rgba(249,115,22,0.3)] transition-all hover:scale-105 active:scale-95 relative z-10">
               Invite Affiliates
            </Link>
        </div>
      ) : (
        <>
        <div className="mb-10">
          <h3 className="text-xl font-bold text-zinc-100 flex items-center gap-2 mb-4">
            <Target className="w-6 h-6 text-orange-400" />
            Grow your affiliate revenue
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="bg-zinc-900 border-zinc-800/80 shadow-lg group transition-all duration-300 hover:border-orange-500/50 hover:shadow-[0_0_30px_rgba(249,115,22,0.1)] flex flex-col justify-between overflow-hidden">
              <CardHeader className="pb-2 pt-5">
                <CardTitle className="text-lg font-bold text-zinc-100 group-hover:text-orange-400 transition-colors">Invite 5 more affiliates</CardTitle>
                <p className="text-sm text-zinc-400 mt-1">Grow your sales team organically.</p>
              </CardHeader>
              <CardContent className="pt-2 pb-5">
                  <Link href="/admin/affiliates" className="w-full flex items-center justify-center bg-zinc-800/80 hover:bg-zinc-700 text-zinc-100 font-semibold py-2.5 rounded-lg transition-colors border border-zinc-700/50">
                      Invite Now
                  </Link>
              </CardContent>
            </Card>
            
            <Card className="bg-zinc-900 border-zinc-800/80 shadow-lg group transition-all duration-300 hover:border-amber-500/50 hover:shadow-[0_0_30px_rgba(251,191,36,0.1)] flex flex-col justify-between overflow-hidden">
              <CardHeader className="pb-2 pt-5">
                <CardTitle className="text-lg font-bold text-zinc-100 group-hover:text-amber-400 transition-colors">Create a new campaign</CardTitle>
                <p className="text-sm text-zinc-400 mt-1">Test higher commission incentives.</p>
              </CardHeader>
              <CardContent className="pt-2 pb-5">
                  <Link href="/admin/campaigns" className="w-full flex items-center justify-center bg-zinc-800/80 hover:bg-zinc-700 text-zinc-100 font-semibold py-2.5 rounded-lg transition-colors border border-zinc-700/50">
                      Create Campaign
                  </Link>
              </CardContent>
            </Card>

            <Card className="bg-zinc-900 border-zinc-800/80 shadow-lg group transition-all duration-300 hover:border-indigo-500/50 hover:shadow-[0_0_30px_rgba(99,102,241,0.1)] flex flex-col justify-between overflow-hidden">
              <CardHeader className="pb-2 pt-5">
                <CardTitle className="text-lg font-bold text-zinc-100 group-hover:text-indigo-400 transition-colors">Share your signup page</CardTitle>
                <p className="text-sm text-zinc-400 mt-1">Drop this link in your site's footer.</p>
              </CardHeader>
              <CardContent className="pt-2 pb-5 flex gap-2">
                  <div className="flex-1 w-full bg-zinc-800/80 hover:bg-zinc-700/80 rounded-lg transition-colors border border-zinc-700/50 relative">
                    <CopyButton text={portalUrl} className="w-full h-full min-h-[42px] absolute inset-0 text-zinc-100 font-semibold shadow-none opacity-0" />
                    <div className="w-full h-full min-h-[42px] flex items-center justify-center text-sm font-semibold pointer-events-none">
                      Copy Link
                    </div>
                  </div>
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="mb-10 bg-indigo-500/10 border border-indigo-500/20 rounded-2xl p-6 flex items-start gap-5 scale-100 hover:scale-[1.01] transition-transform">
          <div className="bg-indigo-500/20 p-2.5 rounded-xl border border-indigo-500/30">
              <Lightbulb className="w-6 h-6 text-indigo-400" />
          </div>
          <div>
              <h4 className="text-indigo-300 font-bold mb-1.5 text-lg tracking-wide">Growth Tip</h4>
              <p className="text-indigo-200/80 font-medium leading-relaxed">
                  You have {affiliatesCount || 0} affiliates but only a few might be actively driving sales right now. 
                  Consider reaching out to inactive affiliates with a new campaign or exclusive asset bundle to re-engage them.
              </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
          <Card className="bg-zinc-900 border-zinc-800/80 shadow-xl transition-all duration-300 hover:border-zinc-700 group py-1 relative overflow-hidden">
            <div className="absolute -right-20 -top-20 w-40 h-40 bg-amber-500/5 rounded-full blur-3xl pointer-events-none" />
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                <DollarSign className="w-4 h-4 text-amber-500" /> Affiliate Revenue
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold text-zinc-50 tracking-tight">
                $<CountUp end={estimatedRevenue} decimals={2} />
              </div>
              <p className="text-xs text-amber-500 font-medium mt-2 flex items-center gap-2">
                <span className="bg-amber-500/10 px-1.5 py-0.5 rounded border border-amber-500/20">+12.5%</span> this week
              </p>
            </CardContent>
          </Card>

          <Card className="bg-zinc-900 border-zinc-800/80 shadow-xl transition-all duration-300 hover:border-zinc-700 group py-1 relative overflow-hidden">
            <div className="absolute -right-20 -top-20 w-40 h-40 bg-orange-500/5 rounded-full blur-3xl pointer-events-none" />
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                <Target className="w-4 h-4 text-orange-500" /> Clicks from Affiliates
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold text-zinc-50 tracking-tight">
                <CountUp end={totalClicks} />
              </div>
              <p className="text-xs text-orange-500 font-medium mt-2 flex items-center gap-2">
                <span className="bg-orange-500/10 px-1.5 py-0.5 rounded border border-orange-500/20">↑</span> trending up
              </p>
            </CardContent>
          </Card>

          <Card className="bg-zinc-900 border-zinc-800/80 shadow-xl transition-all duration-300 hover:border-zinc-700 group py-1 relative overflow-hidden">
            <div className="absolute -right-20 -top-20 w-40 h-40 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
                <Users className="w-4 h-4 text-emerald-500" /> Active Affiliates
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-bold text-zinc-50 tracking-tight">
                <CountUp end={affiliatesCount || 0} />
              </div>
              <p className="text-xs text-emerald-500 font-medium mt-2 flex items-center gap-2">
                <span className="bg-emerald-500/10 px-1.5 py-0.5 rounded border border-emerald-500/20">+3</span> this month
              </p>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
          <Card className="bg-zinc-900 border-zinc-800/80 shadow-xl group hover:border-zinc-700 transition-colors duration-300 h-72 relative overflow-hidden">
            <div className="absolute -right-20 -top-20 w-64 h-64 bg-amber-500/5 rounded-full blur-3xl pointer-events-none" />
            <CardHeader className="border-b border-zinc-800/50 pb-4">
              <div className="flex justify-between items-center">
                <CardTitle className="text-sm font-semibold text-zinc-200">Revenue from affiliates</CardTitle>
                <select className="bg-zinc-950 border border-zinc-800 text-xs px-3 py-1.5 rounded-md text-zinc-300 focus:outline-none focus:ring-1 focus:ring-amber-500 transition-all cursor-pointer hover:bg-zinc-800 relative z-10 w-[120px]">
                  <option>Last 7 days</option>
                  <option>Last 30 days</option>
                  <option>All time</option>
                </select>
              </div>
              <div className="text-2xl font-bold text-zinc-100 mt-2 flex items-center gap-2">
                $<CountUp end={estimatedRevenue} decimals={2} />
              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-center h-40">
              <div className="w-full h-full relative flex items-end opacity-50 group-hover:opacity-100 transition-opacity duration-500">
                <svg className="absolute inset-0 h-full w-full" preserveAspectRatio="none" viewBox="0 0 100 100">
                  <path d="M0,80 L20,60 L40,70 L60,30 L80,45 L100,10" fill="none" stroke="#fbbf24" strokeWidth="2" vectorEffect="non-scaling-stroke"></path>
                  <path d="M0,80 L20,60 L40,70 L60,30 L80,45 L100,10 L100,100 L0,100 Z" fill="url(#amber-gradient)" opacity="0.1"></path>
                  <defs>
                    <linearGradient id="amber-gradient" x1="0" x2="0" y1="0" y2="1">
                      <stop offset="0%" stopColor="#fbbf24" />
                      <stop offset="100%" stopColor="transparent" />
                    </linearGradient>
                  </defs>
                </svg>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-zinc-900 border-zinc-800/80 shadow-xl group hover:border-zinc-700 transition-colors duration-300 h-72 relative overflow-hidden">
            <div className="absolute -left-20 -bottom-20 w-64 h-64 bg-orange-500/5 rounded-full blur-3xl pointer-events-none" />
            <CardHeader className="border-b border-zinc-800/50 pb-4">
              <div className="flex justify-between items-center">
                <CardTitle className="text-sm font-semibold text-zinc-200">Commissions to pay</CardTitle>
                <select className="bg-zinc-950 border border-zinc-800 text-xs px-3 py-1.5 rounded-md text-zinc-300 focus:outline-none focus:ring-1 focus:ring-orange-500 transition-all cursor-pointer hover:bg-zinc-800 relative z-10 w-[120px]">
                  <option>Last 7 days</option>
                  <option>Last 30 days</option>
                  <option>All time</option>
                </select>
              </div>
              <div className="text-2xl font-bold text-zinc-100 mt-2 flex items-center gap-2">
                $<CountUp end={totalCommissions} decimals={2} />
              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-center h-40">
              <div className="w-full h-full relative flex items-end opacity-50 group-hover:opacity-100 transition-opacity duration-500">
                <svg className="absolute inset-0 h-full w-full" preserveAspectRatio="none" viewBox="0 0 100 100">
                  <path d="M0,90 L25,65 L50,80 L75,40 L100,50" fill="none" stroke="#f97316" strokeWidth="2" vectorEffect="non-scaling-stroke"></path>
                  <path d="M0,90 L25,65 L50,80 L75,40 L100,50 L100,100 L0,100 Z" fill="url(#orange-gradient)" opacity="0.1"></path>
                  <defs>
                    <linearGradient id="orange-gradient" x1="0" x2="0" y1="0" y2="1">
                      <stop offset="0%" stopColor="#f97316" />
                      <stop offset="100%" stopColor="transparent" />
                    </linearGradient>
                  </defs>
                </svg>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Recent Referrals */}
        <Card className="bg-zinc-900 border-zinc-800/80 shadow-2xl group hover:border-zinc-700 transition-colors duration-300 relative overflow-hidden">
          <CardHeader className="border-b border-zinc-800/50 pb-5 pt-6 flex flex-row items-center justify-between">
            <CardTitle className="text-sm font-bold text-zinc-200 tracking-wide flex items-center gap-2">
              <GitMerge className="w-4 h-4 text-zinc-400" /> Recent Referrals
            </CardTitle>
            <Link
              href="/admin/referrals"
              className="flex items-center gap-1 text-xs text-zinc-400 hover:text-white bg-zinc-800 hover:bg-zinc-700 px-3 py-1.5 rounded transition-colors font-medium border border-zinc-700"
            >
              View All <ArrowRight className="w-3 h-3" />
            </Link>
          </CardHeader>
          <CardContent className="p-0">
            {!recentReferrals || recentReferrals.length === 0 ? (
              <p className="px-6 py-12 text-center text-zinc-500 font-medium">No referrals driving sales yet.</p>
            ) : (
              <div className="divide-y divide-zinc-800/50">
                {recentReferrals.map((ref) => {
                  const aff = ref.affiliate as any;
                  const email = ref.customer_email || "—";
                  return (
                      <div key={ref.id} className="flex items-center justify-between px-6 py-4 hover:bg-zinc-800/30 transition-colors group/row">
                        <div className="flex items-center gap-4 min-w-0">
                          <div className={`w-2 h-2 rounded-full shrink-0 ${
                            ref.status === "active" || ref.status === 'paid' ? "bg-emerald-500 shadow-[0_0_8px_rgba(52,211,153,0.6)]" : "bg-zinc-600"
                          }`} />
                          <div className="min-w-0 flex flex-col">
                            <span className="font-semibold text-zinc-200 truncate flex items-center gap-2 mb-1">
                                {email} 
                                <span className="text-xs px-2 py-0.5 rounded-full bg-zinc-800 text-zinc-400 border border-zinc-700 font-mono tracking-wide hidden sm:inline-block">
                                    {(ref.totalRevenue || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' })}
                                </span>
                            </span>
                            <div className="flex items-center gap-2">
                                <span className="text-[11px] text-zinc-500">Referred by</span>
                                {aff ? (
                                    <AffiliateQuickViewButton affiliate={aff} compact campaigns={campaigns || []} />
                                ) : (
                                    <span className="text-[11px] text-zinc-500 font-medium">Unknown Affiliate</span>
                                )}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-5 shrink-0 ml-4">
                          <div className="flex flex-col items-end border-r border-zinc-800/50 pr-5 hidden sm:flex">
                            <span className="text-xs font-bold text-orange-400/90 font-mono tracking-wide">
                              +${(ref.totalCommission || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                            </span>
                          </div>
                          <span className={`text-[10px] px-2 py-1 rounded font-bold uppercase tracking-wider border ${
                            ref.status === "active" || ref.status === 'paid'
                              ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
                              : "bg-amber-500/10 text-amber-500 border-amber-500/30"
                          }`}>{ref.status === 'active' || ref.status === 'paid' ? 'Paid' : 'Pending'}</span>
                          <span className="text-[11px] text-zinc-500 font-mono tracking-wide hidden sm:block">
                            {new Date(ref.created_at).toLocaleDateString("en-US", { month: "short", day: "2-digit" })}
                          </span>
                          {aff && (
                            <div className="ml-1 inline-block opacity-0 group-hover/row:opacity-100 transition-opacity">
                              <AffiliateActionsCell affiliate={aff} campaigns={campaigns || []} />
                            </div>
                          )}
                        </div>
                      </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
        </>
      )}
    </div>
  );
}
