import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/utils/supabase/server";
import { CopyButton } from "@/components/CopyButton";
import { Target, Users, DollarSign, GitMerge, ArrowRight, Lightbulb } from "lucide-react";
import Link from "next/link";
import { AffiliateQuickViewButton } from "@/app/(admin)/admin/referrals/AffiliateQuickViewButton";
import { AffiliateActionsCell } from "@/app/(admin)/admin/affiliates/AffiliateActionsCell";
import { ReferralActionsCell } from "@/app/(admin)/admin/referrals/ReferralActionsCell";
import { AdminSetupChecklist } from "./AdminSetupChecklist";
import { CountUp } from "@/components/CountUp";
import { DismissibleAlert } from "@/components/DismissibleAlert";

export default async function AdminDashboard() {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  const { data: org } = await supabase
    .from('organizations')
    .select('id, stripe_webhook_id, custom_domain')
    .eq('owner_id', user?.id || 'NO_USER')
    .limit(1)
    .maybeSingle();

  const orgId = org?.id;

  if (!orgId) {
      return (
          <div className="flex h-full items-center justify-center p-8">
              <div className="bg-zinc-900 border border-red-500/30 text-amber-500/80 px-6 py-4 rounded-xl shadow-xl max-w-md text-center text-sm font-mono tracking-wide">
                  Organization configuration missing or unauthorized. Please verify your platform status.
              </div>
          </div>
      );
  }

  const portalUrl = org?.custom_domain ? `https://${org.custom_domain}` : (process.env.NEXT_PUBLIC_SITE_URL || "https://affiliatemango.com");

  // Fetch real aggregated data
  const { count: affiliatesCount } = await supabase
    .from('affiliates')
    .select('*', { count: 'exact', head: true })
    .eq('org_id', orgId);

  const { data: stats } = await supabase
    .from('affiliates')
    .select('clicks, total_commission')
    .eq('org_id', orgId);

  const totalClicks = stats?.reduce((acc, curr) => acc + (curr.clicks || 0), 0) || 0;
  const totalCommissions = stats?.reduce((acc, curr) => acc + Number(curr.total_commission || 0), 0) || 0;
  const estimatedRevenue = totalCommissions * 3.33; // Mock expansion factor

  const { count: referralsCount } = await supabase
    .from('referrals')
    .select('*', { count: 'exact', head: true })
    .eq('org_id', orgId);

  const { data: campaigns } = await supabase.from("campaigns").select("*").eq('org_id', orgId);

  // Recent referrals (actually recent sales/commissions) mapped to precise events
  const { data: recentCommissions } = await supabase
    .from("commissions")
    .select("id, amount, revenue, status, affiliate_id, created_at, customer_email, referral:referrals(customer_email)")
    .eq('org_id', orgId)
    .order("created_at", { ascending: false })
    .limit(8);

  const recentAffIds = [...new Set((recentCommissions || []).map((c: any) => c.affiliate_id).filter(Boolean))];
  const { data: recentAffiliates } = recentAffIds.length > 0
    ? await supabase.from("affiliates").select("*").in("id", recentAffIds)
    : { data: [] };

  const recentAffMap: Record<string, any> = {};
  for (const a of recentAffiliates || []) recentAffMap[a.id] = a;

  // Track settlements to know if these are "paid" or "pending" dynamically
  const { data: recentPayouts } = await supabase.from("payouts").select("affiliate_id, created_at").eq("org_id", orgId);
  const payoutMap: Record<string, Date[]> = {};
  for (const p of recentPayouts || []) {
      if (!payoutMap[p.affiliate_id]) payoutMap[p.affiliate_id] = [];
      payoutMap[p.affiliate_id].push(new Date(p.created_at));
  }

  const recentReferrals = (recentCommissions || []).map((c: any) => {
    let email = c.customer_email;
    if (!email && c.referral && !Array.isArray(c.referral)) {
        email = c.referral.customer_email || "Unknown";
    }

    const dates = payoutMap[c.affiliate_id] || [];
    const commDate = new Date(c.created_at);
    const settled = dates.some(pd => pd >= commDate);
    const effectiveStatus = settled ? 'paid' : (c.status || 'pending');

    return {
      id: c.id,
      customer_email: email,
      status: effectiveStatus,
      totalRevenue: Number(c.revenue || 0),
      totalCommission: Number(c.amount || 0),
      affiliate: c.affiliate_id ? recentAffMap[c.affiliate_id] ?? null : null,
      created_at: c.created_at
    };
  });

  return (
    <div className="space-y-6 w-full max-w-full font-sans pb-10">
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 mb-10 mt-2">
        <div>
          <h2 className="text-4xl md:text-[3.5rem] font-extrabold text-white tracking-tight leading-tight">
            <CountUp end={estimatedRevenue} prefix="$" decimals={2} />
          </h2>
          <p className="text-xl text-zinc-400 font-medium mt-3 tracking-tight">
            generated by your affiliates
          </p>
          <div className="text-sm text-emerald-400 font-medium mt-4 flex items-center gap-2 bg-emerald-500/10 px-3 py-1.5 rounded-full inline-flex border border-emerald-500/20">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.8)] animate-pulse" />
            <CountUp end={affiliatesCount || 0} /> affiliates actively sending traffic
          </div>
        </div>
        <div className="flex flex-col items-end gap-3 shrink-0">
          <select className="bg-zinc-900 border border-zinc-800 text-sm px-4 py-2 hover:bg-zinc-800 rounded-lg text-zinc-300 focus:outline-none focus:ring-1 focus:ring-orange-500 transition-all cursor-pointer w-full md:w-auto text-right font-medium">
            <option>Last 7 days</option>
            <option>Last 30 days</option>
            <option>All time</option>
          </select>
        </div>
      </div>

      <AdminSetupChecklist 
        hasCampaign={!!(campaigns && campaigns.length > 0)}
        hasAffiliate={!!(affiliatesCount && affiliatesCount > 0)}
        hasClicks={totalClicks > 0}
        hasStripe={!!org?.stripe_webhook_id}
      />

      {(!affiliatesCount || affiliatesCount === 0) ? (
        <div className="bg-zinc-900 border border-zinc-800/80 rounded-xl py-20 px-6 text-center shadow-2xl relative overflow-hidden mt-8 mb-10">
            <h3 className="text-3xl font-extrabold text-zinc-100 mb-4 relative z-10 tracking-tight">You don't have affiliates yet</h3>
            <p className="text-lg text-zinc-400 mb-8 max-w-xl mx-auto relative z-10 font-medium">Start by inviting your first 5 affiliates to kick off your growth engine.</p>
            <Link href="/admin/affiliates" className="inline-flex items-center justify-center bg-orange-500 hover:bg-orange-400 text-orange-950 font-extrabold px-8 py-4 rounded-xl shadow-[0_0_25px_rgba(249,115,22,0.3)] transition-all hover:scale-105 active:scale-95 relative z-10">
               Invite Affiliates
            </Link>
        </div>
      ) : (
        <>
        <div className="mb-10">
          <h3 className="text-xl font-bold text-zinc-100 flex items-center gap-2 mb-5">
            <Target className="w-5 h-5 text-orange-400" />
            Grow your affiliate revenue
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            <Card className="bg-zinc-900/50 border-zinc-800 shadow-sm transition-all duration-300 rounded-xl group relative overflow-hidden">
              <CardHeader className="pb-3 pt-6 px-6">
                <CardTitle className="text-base font-bold text-zinc-100 group-hover:text-orange-400 transition-colors">Invite Affiliates</CardTitle>
                <p className="text-[13px] text-zinc-400 mt-1 font-medium leading-relaxed">Grow your sales team organically by bringing more partners on board.</p>
              </CardHeader>
              <CardContent className="pt-2 pb-6 px-6">
                  <Link href="/admin/affiliates" className="w-full flex items-center justify-center bg-orange-500 hover:bg-orange-400 text-orange-950 font-bold py-2.5 rounded-lg transition-all text-sm">
                      Invite Now
                  </Link>
              </CardContent>
            </Card>
            
            <Card className="bg-zinc-900/50 border-zinc-800 shadow-sm transition-all duration-300 rounded-xl group relative overflow-hidden">
              <CardHeader className="pb-3 pt-6 px-6">
                <CardTitle className="text-base font-bold text-zinc-100 group-hover:text-zinc-300 transition-colors">Launch Campaigns</CardTitle>
                <p className="text-[13px] text-zinc-400 mt-1 font-medium leading-relaxed">Test higher commission incentives to dramatically boost conversions.</p>
              </CardHeader>
              <CardContent className="pt-2 pb-6 px-6">
                  <Link href="/admin/campaigns" className="w-full flex items-center justify-center bg-zinc-800 text-zinc-300 hover:bg-zinc-700 hover:text-white font-bold py-2.5 rounded-lg border border-zinc-700 transition-all text-sm">
                      Create Campaign
                  </Link>
              </CardContent>
            </Card>

            <Card className="bg-zinc-900/50 border-zinc-800 shadow-sm transition-all duration-300 rounded-xl group relative overflow-hidden">
              <CardHeader className="pb-3 pt-6 px-6">
                <CardTitle className="text-base font-bold text-zinc-100 group-hover:text-zinc-300 transition-colors">Share Signup Page</CardTitle>
                <p className="text-[13px] text-zinc-400 mt-1 font-medium leading-relaxed">Drop this link in your site's footer to capture inbound partners.</p>
              </CardHeader>
              <CardContent className="pt-2 pb-6 px-6 flex gap-2">
                  <div className="flex-1 w-full bg-transparent hover:bg-zinc-800 rounded-lg transition-all border border-zinc-800 hover:border-zinc-700 relative overflow-hidden text-sm">
                    <CopyButton text={portalUrl} className="w-full h-full min-h-[40px] absolute inset-0 text-zinc-300 font-bold shadow-none opacity-0" />
                    <div className="w-full h-full min-h-[40px] flex items-center justify-center font-bold pointer-events-none text-zinc-400 group-hover:text-zinc-300 transition-colors">
                      Copy Link
                    </div>
                  </div>
              </CardContent>
            </Card>
          </div>
        </div>

        <DismissibleAlert id="dashboard-growth-tip-1" className="mb-10 bg-zinc-900/50 border border-zinc-800 rounded-xl p-5 flex items-start gap-4 transition-all">
          <div className="bg-zinc-800 p-2.5 rounded-lg border border-zinc-700 flex-shrink-0">
              <Lightbulb className="w-5 h-5 text-amber-500" />
          </div>
          <div className="pr-8">
              <h4 className="text-zinc-200 font-bold mb-1 text-sm tracking-wide flex items-center gap-2">
                  Growth Tip
              </h4>
              <p className="text-zinc-400 text-sm font-medium leading-relaxed">
                  You have {affiliatesCount || 0} affiliates but only a few might be actively driving sales right now. 
                  Consider reaching out to inactive affiliates with a new campaign or exclusive asset bundle to re-engage them.
              </p>
          </div>
        </DismissibleAlert>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-10">
          <Card className="bg-zinc-900 border-zinc-800 shadow-sm transition-all duration-300 rounded-xl overflow-hidden px-6 pt-6 pb-5">
            <div className="text-xs font-bold text-zinc-400 flex items-center gap-2 mb-3 uppercase tracking-wider">
              <GitMerge className="w-4 h-4 text-emerald-500" /> Total Referrals
            </div>
            <div className="text-4xl font-extrabold text-white tracking-tight mb-2">
              <CountUp end={referralsCount || 0} />
            </div>
            <p className="text-xs font-medium flex items-center gap-1.5 pt-2">
              <span className="text-emerald-400">Stable</span> 
              <span className="text-zinc-500 text-[11px] uppercase tracking-wider">Historical Total</span>
            </p>
          </Card>

          <Card className="bg-zinc-900 border-zinc-800 shadow-sm transition-all duration-300 rounded-xl overflow-hidden px-6 pt-6 pb-5">
            <div className="text-xs font-bold text-zinc-400 flex items-center gap-2 mb-3 uppercase tracking-wider">
              <Target className="w-4 h-4 text-orange-500" /> Clicks (All Time)
            </div>
            <div className="text-4xl font-extrabold text-white tracking-tight mb-2">
              <CountUp end={totalClicks} />
            </div>
            <p className="text-xs font-medium flex items-center gap-1.5 pt-2">
              <span className="text-emerald-400 text-[10px]">↑</span> 
              <span className="text-zinc-500 text-[11px] uppercase tracking-wider">Trending Up</span>
            </p>
          </Card>

          <Card className="bg-zinc-900 border-zinc-800 shadow-sm transition-all duration-300 rounded-xl overflow-hidden px-6 pt-6 pb-5">
            <div className="text-xs font-bold text-zinc-400 flex items-center gap-2 mb-3 uppercase tracking-wider">
              <Users className="w-4 h-4 text-indigo-400" /> Active Affiliates
            </div>
            <div className="text-4xl font-extrabold text-white tracking-tight mb-2">
              <CountUp end={affiliatesCount || 0} />
            </div>
            <p className="text-xs font-medium flex items-center gap-1.5 pt-2">
              <span className="text-zinc-400 font-bold">+3</span> 
              <span className="text-zinc-500 text-[11px] uppercase tracking-wider">This Month</span>
            </p>
          </Card>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-10">
          <Card className="bg-zinc-900 border-zinc-800/80 shadow-sm rounded-xl relative overflow-hidden flex flex-col pt-5 pb-0 px-0">
            <div className="px-6 flex justify-between items-center bg-transparent mb-6">
              <div>
                <h3 className="text-xs font-bold text-zinc-400 uppercase tracking-wider">Conversion Trend</h3>
              </div>
            </div>
            <div className="flex-grow flex items-end justify-center w-full px-6 relative">
              <div className="absolute left-6 right-6 top-0 bottom-8 border-b-2 border-l-2 border-zinc-800/50">
                  <span className="absolute -left-2 top-0 text-[10px] font-mono text-zinc-500 -translate-x-full">High</span>
                  <span className="absolute -left-2 bottom-0 text-[10px] font-mono text-zinc-500 -translate-x-full translate-y-1/2">Low</span>
                  <div className="absolute bottom-[-24px] w-full flex justify-between text-[10px] font-mono text-zinc-500 items-end px-1">
                      <span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span>
                  </div>
              </div>
              <div className="w-full h-full relative flex items-end pb-8 pl-[2px] z-10">
                <svg className="absolute inset-0 h-[calc(100%-2rem)] w-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 100">
                  <path d="M0,80 L16.6,60 L33.3,70 L50,30 L66.6,45 L83.3,10 L100,50" fill="none" stroke="#fbbf24" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"></path>
                </svg>
              </div>
            </div>
          </Card>

          <Card className="bg-zinc-900 border-zinc-800/80 shadow-sm rounded-xl relative overflow-hidden flex flex-col pt-5 pb-0 px-0">
            <div className="px-6 flex justify-between items-center bg-transparent mb-6">
              <div>
                <h3 className="text-xs font-bold text-zinc-400 uppercase tracking-wider">Unpaid Commissions Activity</h3>
              </div>
            </div>
            <div className="flex-grow flex items-end justify-center w-full px-6 relative">
              <div className="absolute left-6 right-6 top-0 bottom-8 border-b-2 border-l-2 border-zinc-800/50">
                  <span className="absolute -left-2 top-0 text-[10px] font-mono text-zinc-500 -translate-x-full">Peak</span>
                  <span className="absolute -left-2 bottom-0 text-[10px] font-mono text-zinc-500 -translate-x-full translate-y-1/2">Min</span>
                  <div className="absolute bottom-[-24px] w-full flex justify-between text-[10px] font-mono text-zinc-500 px-1">
                      <span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span>
                  </div>
              </div>
              <div className="w-full h-full relative flex items-end pb-8 pl-[2px] z-10">
                <svg className="absolute inset-0 h-[calc(100%-2rem)] w-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 100">
                  <path d="M0,90 L20,70 L40,80 L60,40 L80,50 L100,10" fill="none" stroke="#f97316" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"></path>
                </svg>
              </div>
            </div>
          </Card>
        </div>

        {/* Recent Referrals */}
        <Card className="bg-zinc-900 border-zinc-800/50 shadow-2xl rounded-2xl group hover:border-zinc-700/80 transition-colors duration-300 relative overflow-hidden">
          <CardHeader className="border-b border-zinc-800/50 pb-5 pt-6 px-6 flex flex-row items-center justify-between bg-zinc-950/20">
            <CardTitle className="text-sm font-bold text-zinc-200 tracking-wide flex items-center gap-2">
              <GitMerge className="w-4 h-4 text-zinc-400" /> Recent Referrals
            </CardTitle>
            <Link
              href="/admin/referrals"
              className="flex items-center gap-1.5 text-xs text-zinc-300 hover:text-white bg-zinc-800 hover:bg-zinc-700 px-4 py-2 rounded-lg transition-colors font-bold border border-zinc-700"
            >
              View All <ArrowRight className="w-3 h-3" />
            </Link>
          </CardHeader>
          <CardContent className="p-0">
            {!recentReferrals || recentReferrals.length === 0 ? (
              <p className="px-6 py-16 text-center text-zinc-500 font-medium">No referrals driving sales yet.</p>
            ) : (
              <div className="divide-y divide-zinc-800/40">
                {recentReferrals.map((ref) => {
                  const aff = ref.affiliate as any;
                  const email = ref.customer_email || "—";
                  return (
                      <div key={ref.id} className="flex items-center justify-between px-6 py-4 hover:bg-zinc-800/20 transition-colors group/row">
                        <div className="flex items-center gap-4 min-w-0">
                          <div className={`w-2 h-2 rounded-full shrink-0 ${
                            ref.status === "active" || ref.status === 'paid' ? "bg-emerald-500 shadow-[0_0_8px_rgba(52,211,153,0.6)]" : "bg-zinc-600"
                          }`} />
                          <div className="min-w-0 flex flex-col">
                            <span className="font-bold text-zinc-200 truncate flex items-center gap-2 mb-1">
                                {email} 
                                <span className="text-xs px-2.5 py-0.5 rounded-md bg-zinc-800 text-zinc-400 border border-zinc-700/80 font-mono tracking-wide hidden sm:inline-block">
                                    {(ref.totalRevenue || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' })}
                                </span>
                            </span>
                            <div className="flex items-center gap-2">
                                <span className="text-[11px] text-zinc-500 font-medium">Referred by</span>
                                {aff ? (
                                    <AffiliateQuickViewButton affiliate={aff} compact campaigns={campaigns || []} />
                                ) : (
                                    <span className="text-[11px] text-zinc-500 font-medium">Unknown Affiliate</span>
                                )}
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-6 shrink-0 ml-4">
                          <div className="flex flex-col items-end border-r border-zinc-800/40 pr-6 hidden sm:flex">
                            <span className="text-sm font-bold text-orange-400 font-mono tracking-wide">
                              +${(ref.totalCommission || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                            </span>
                          </div>
                          <span className={`text-[10px] px-2.5 py-1 rounded font-bold uppercase tracking-wider border ${
                            ref.status === "active" || ref.status === 'paid'
                              ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
                              : "bg-amber-500/10 text-amber-500 border-amber-500/30"
                          }`}>{ref.status === 'active' || ref.status === 'paid' ? 'Paid' : 'Pending'}</span>
                          <span className="text-[11px] text-zinc-500 font-mono tracking-wide hidden lg:block">
                            {new Date(ref.created_at).toLocaleDateString("en-US", { month: "short", day: "2-digit" })}
                          </span>
                          {aff && (
                            <div className="ml-1 inline-block opacity-0 group-hover/row:opacity-100 transition-opacity">
                                <ReferralActionsCell referral={ref} />
                            </div>
                          )}
                        </div>
                      </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
        </>
      )}
    </div>
  );
}
